version: '3.8'

services:
  app:
    container_name: password-manager-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: password-manager-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
