export const RESPONSE = {
  SUCCESS: 'SUCCESS',
  BAD_REQUEST: 'BAD_REQUEST',
  FAILURE: 'FAILURE',
  UNAUTHORIZED: 'UNAUTHORIZED',
};

export const RESPONSE_STATUS_CODE = {
  '200': 'SUCCESS',
  '400': 'BAD_REQUEST',
  '401': 'UNAUTHORIZED',
  '500': 'FAILURE',
};
